pipeline {
    agent any

    stages {
        stage('docker Build') {
            steps {
                sh """
                    cd src/frontend
                    podman system migrate
                    loginctl enable-linger 974
                    podman system migrate
                    docker pull python
                """
            }
        }
    }
}
