pipeline {
    agent any

    stages {
        stage('docker Build') {
            steps {
                sh """
                    cd src/frontend
                    docker build -t frontend .
                """
            }
        }
    }
}
